### ISSUE TITLE
Model missing density profiles

### ISSUE THREAD

**Issue by loic-a** [p201-sp2016/NestedSampling_DMD#14]
I only seem to find the NFW profile, and don't see the 4 density profiles discussed in the model intro.

**Comment by vnmanoharan** [comment]
It looks like this still hasn't been fixed, so I'm reopening the issue.  I see only only the NFW profile in the latest revision, and not the 3 others.  If I'm missing something please comment.

**Comment by vnmanoharan** [comment]
I still don't understand why this issue has been closed.  It seems that model.py still only contains the NFW profile.

**Comment by dseitova** [comment]
File model0425 (the updated model.py file) contains all 4 density profiles

**Comment by vnmanoharan** [comment]
The code for the models needs to be in the package itself (i.e., in model.py) rather than in the notebook file.  The notebook file is not part of the python package, and its code is not accessible to someone who does "import nsdmd".

**Comment by lwilliams93** [comment]
Agreed

**Comment by JunYinDM** [comment]
ok ... finally ... this could be closed as well
