### ISSUE TITLE
cleanup required

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/NestedSampling_DMD#19]
There is some [cruft](https://en.wikipedia.org/wiki/Cruft) that should be deleted and added to .gitignore:
- `nsdmd/nsdmd` (empty directory)
- `nsdmd/__pycache__` (directory that is automatically created by python)

**Comment by vnmanoharan** [comment]
Also `.ipynb_checkpoints` directory in the root folder can be deleted and added to .gitignore.

**Comment by JunYinDM** [comment]
We could manually clean up things but I am actually very confused at here. When I do git commit, it automatically creates the ipynb_checkpoints [TRASH] file. And I am not able to see this in the terminal. I can only see/delete this on the github webpage. 

I am not sure what I did wrong and how to improve this other than manually deleting it ... 

Any thoughts? 
thanks 



======example ====================================================
marginmatoMacBook-Pro:nsdmd margin$ git add .
marginmatoMacBook-Pro:nsdmd margin$ git commit -m "update tutorial"
[master eef1090] update tutorial
 4 files changed, 1646 insertions(+), 1193 deletions(-)
 create mode 100644 .ipynb_checkpoints/model-checkpoint.ipynb
 delete mode 100644 testing.ipynb
marginmatoMacBook-Pro:nsdmd margin$ git push
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 626 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/p201-sp2016/nsdmd.git
   60c0ce5..eef1090  master -> master
marginmatoMacBook-Pro:nsdmd margin$

**Comment by JunYinDM** [comment]
thanks Dear Prof.Manoharan , 

I am still bit confused here. What do you mean by "Also .ipynb_checkpoints directory in the root folder can be deleted and added to .gitignore."

Right now in the .gitignore file, the last two lines are, 
 +#Ipython Notebook
 +.ipynb_checkpoints

whenever I tries to git commit, it automatically creates the .ipynb_checkpoints file. Should change .gitignore into a director and change include the .ipynb_checkpoints inside that? But .ipynb_checkpoints just includes all the new updates ... 

so what should I do here? 

thank you.

**Comment by vnmanoharan** [comment]
@ralex0 could you please help with this?

**Comment by ralex0** [comment]
You have to ignore it by putting it in the .gitignore and also make sure git stops tracking the file (already done). I use GitKraken which automatically asks if I want to untrack when I delete things. The corresponding command for untracking is `git rm -r --cached .ipynb_checkpoints/` if you run this command in the GitHub app, this will also make sure it's not added when you commit.
