### ISSUE TITLE
tutorial.ipynb needs to be a tutorial

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/NestedSampling_DMD#22]
Right now it is simply a copy of model.ipynb.  It needs to explain what the user should input to the package and what the package will compute.  As we discussed previously, the input from the user should be the priors to be used in the model comparison.  

To make things clear: model.ipynb is a place for explaining the models, and tutorial.ipynb is a place for explaining the package.

**Comment by JunYinDM** [comment]
hopefully it mostly looks like a tutorial now
