### ISSUE TITLE
model and tutorial notebooks need better explanations

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/NestedSampling_DMD#23]
Right now it's a lot of code and plots, with very little explanation.

**Comment by lwilliams93** [comment]
Agreed. There are few explanations about what the code does, and how to do the inference. Maybe add a step by step about your overall goal and then include inference at the end and show how to use it.

**Comment by JunYinDM** [comment]
thanks 
but 
no longer agreed ...
