### ISSUE TITLE
model.ipynb should describe package, not project

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/NestedSampling_DMD#5]
Remember you are making a python package that anyone can use.  So your documentation (e.g. model.ipynb) should describe the package, not the project. Explain the model for a general audience that might be interested in using your package.

**Comment by JunYinDM** [comment]
thanks dear Prof.Manoharan, 
I am a bit confused by the difference between model.ipynb and tutorial. ipynb. They are both describe how to use the package/model. How should they be different? 

In our model comparison project case, should we introduce all models and their derivations, priors, loglikelihoods and nestle results in the model.ipynb? 
Could we only give an example for one model in the  tutorial. ipynb? 


thanks

**Comment by dseitova** [comment]
I'm working on this, I'll upload everything tomorrow. Jun, I'll email you now

**Comment by vnmanoharan** [comment]
model.ipynb describes the generative model(s).  tutorial.ipynb explains how a user should use the package, and gives an example of a calculation.
