### ISSUE TITLE
model doesn't discuss all parameters

### ISSUE THREAD

**Issue by vnmanoharan** [p201-sp2016/NestedSampling_DMD#6]
Since priors are crucial to your analysis, the model.ipynb file really needs to specify all of the parameters used in the models.  For example, I think you are missing a scaling parameter for each of the models. You use the "proportional to" sign in the equations of the models, but you will need a $\rho_0$ or similar parameter in front instead.

**Comment by vnmanoharan** [comment]
Still need to add all parameters.

**Comment by JunYinDM** [comment]
thanks 
solved
